export interface Inventory {
  internalID : string, // Generated by system, not user input
  internalBarcode : string, // ITEM-00000

  item: string,
  description: string,
  brand: string,
  color:string,
  size: string,
  type: string,
  material:string,
  count: number,
  quantity: number,
  notes: string

  externalBarcode: []; // collection of barcodes from external sources (e.g. manufacturer UPCs) that reference this inventory item
}

export interface SelectOption {
  label: string;
  value: string;
}
