export interface Inventory {
  internalID : string, // Generated by system, not user input
  internalBarcode : string, // ITEM-00000

  item: string,
  description: string,
  brand: string,
  color:string,
  size: string,
  type: string,
  material:string,
  count: number,
  quantity: number,
  notes: string

  externalBarcode?: string[]; // collection of barcodes from external sources (e.g. manufacturer UPCs) that reference this inventory item
}

export interface SelectOption {
  label: string;
  value: string;
}

export interface scanRequest {
  barcode: string;
  // This serves as the input for a scan operation,
  //  which could be either an internal barcode (e.g., "ITEM-00000") or an external barcode (e.g., "MFG-XYZ123").
}

export type scanResult = {
  status: "FOUND"
  item: Inventory;
} | {
  status: "NOT_FOUND"
  barcode: string; // returns the barcode that was scanned but not found
}
