export interface Inventory {
  internalID : string, // Generated by system, not user input
  internalBarcode? : string, // ITEM-00000

  item: string,
  brand: string,
  count: number,
  size: string,
  color:string,
  type: string,
  material:string,
  description: string,
  quantity: number,
  maxQuantity: number,
  minQuantity: number,
  stockState: string,
  notes: string

  externalBarcode?: string[]; // collection of barcodes from external sources (e.g. manufacturer UPCs) that reference this inventory item
}

export interface SelectOption {
  label: string;
  value: string;
}
